name: Dependabot automation

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-auspice-bump:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.triggering_actor.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: pr-info
        run: echo title="$(gh pr view '${{ github.event.workflow_run.pull_requests[0].number }}' --repo '${{ github.repository }}' --json title | jq -r .title)" | tee "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_VICTORLIN_REPO }}
      - if: contains(steps.pr-info.outputs.title, 'bump auspice from')
        run: gh pr merge --repo '${{ github.repository }}' --merge '${{ github.event.workflow_run.pull_requests[0].number }}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_VICTORLIN_REPO }}
